### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bityob** [NickelsLab/Player-Stage-Manual#19]
In this page you have a broken link
http://player-stage-manual.readthedocs.io/en/latest/CONTROLLER_PYCPP/

![image](https://cloud.githubusercontent.com/assets/20026896/16285699/5ee2b9c2-38e0-11e6-8bd7-ae41008d5848.png)

The link in the word 'here' is to:
http://sites.udel.edu/robotics/setting-up-player-and-stage-for-ubuntu-10-04/

But this page doesn't exists any more.

(If you have it somewhere it will be great, because I try to compile the playercpp.py module,
without success yet)

**Comment by knickels** [comment]
Found a similar link - not as step-by-step, but should suffice.
