### ISSUE TITLE
Player make errors in ubuntu 16.04

### ISSUE THREAD

**Issue by Aaricis** [NickelsLab/Player-Stage-Manual#22]
I install Player according to manual, but it can not work.
`Compiling Player ... 

[  1%] Generating player_interfaces.h
[  1%] Built target playercommon
[  1%] Built target playerjpeg
[  1%] Generating playerxdr.?
[  2%] Generating interface_table.h
[  3%] Generating playerc_wrap.h
[  3%] Generating functiontable_gen.h
[  3%] Built target playerc_wrap_i_target
[  3%] Built target player_interfaces
[  3%] Built target playerxdr_src
[  3%] Built target interface_table
[  4%] Built target functiontable_gen
[  5%] Built target playerlogsplitter
[  7%] Built target wavefront_standalone
[  7%] Linking C shared library libplayerwkb.so
[  8%] Built target pmap
[ 10%] Built target playerinterface
Scanning dependencies of target playercore
/usr/bin/ld: can not find -lgeos
collect2: error: ld returned 1 exit status
libplayerwkb/CMakeFiles/playerwkb.dir/build.make:95: recipe for target 'libplayerwkb/libplayerwkb.so.3.1.1-dev' failed
make[2]: *** [libplayerwkb/libplayerwkb.so.3.1.1-dev] Error 1
CMakeFiles/Makefile2:862: recipe for target 'libplayerwkb/CMakeFiles/playerwkb.dir/all' failed
make[1]: *** [libplayerwkb/CMakeFiles/playerwkb.dir/all] Error 2
`

**Comment by knickels** [comment]
Quoting from the documentation - 
> The build process for player and stage is outside the scope of this manual - excellent instructions can be found at http://playerstage.sourceforge.net/doc/Player-3.0.2/player/install.html and http://rtv.github.io/Stage/install.html

**Comment by knickels** [comment]
However - it looks to me like you're missing a prerequisite library - libgeos

http://packages.ubuntu.com/xenial/libgeos-dev
